version: '3.6'

services:
  qa-python:
    image: registry.growfood.pro/qa/python-base-image/base-python:latest
    # depends_on:
    #   - selenoid
#    networks:
#      - selenoid
    volumes:
      - ./features/:/home/behave/
      - ./texts/:/texts/
    logging: &logging
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

#   selenoid:
#     image: registry.growfood.pro/qa/selenoid/selenoids3:latest
#     command: ["-container-network", "selenoid", "-log-output-dir", "/opt/selenoid/logs", "-video-output-dir", "/opt/selenoid/video", "-s3-endpoint", "https://growfood.pro/s3-qa", "-s3-secret-key", "UZjEFWK7Ju6hrEUhLUmW", "-s3-access-key", "s3-qa", "-s3-bucket-name", "s3-qa", "-s3-region", "us-east-2"]
# #    env_file: .env
#     networks:
#       - selenoid
# #    volumes:
# #      - /var/run/docker.sock:/var/run/docker.sock
# #      - /work/selenoid/browsers.json:/etc/selenoid/browsers.json
# #      - ${PWD}/${TEST_NAME}/selenoid/:/opt/selenoid/video/
# #    environment:
# #      - OVERRIDE_VIDEO_OUTPUT_DIR=${PWD}/${TEST_NAME}/selenoid/



#networks:
#  selenoid:
#    external:
#      name: selenoid
